### ISSUE TITLE
There is no space between the footer tag and ending of the page.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/fluidproject.org#15]
When the footer tag ends there is no space between the footer tag and the ending of the page.
By fixing this issue the website will look more good.

**Comment by jhung** [comment]
@aashimgarg, you can fork the repository to your own account and do your work within a branch.

When you are ready, please submit a pull request to this repository so it can be reviewed.

**Comment by aashimgarg** [comment]
Ok @jhung!

**Comment by johntharian** [comment]
Is it okay if i solve this issue?

**Comment by jobara** [comment]
@johntharian I'd hold off on work on this specific issue. I'm not really sure what the bug or feature request is, so it may need more discussion and/or review.

**Comment by ArpitBirSingh** [comment]
![Untitled](https://user-images.githubusercontent.com/66256902/108212590-12b55f80-7154-11eb-9be3-3d3c846dfd12.png)
@jobara Is this ok ??
can i make pull request for this ??

**Comment by jobara** [comment]
@ArpitBirSingh I'd probably hold off. This site is due to be redesigned so things will likely change.

**Comment by jobara** [comment]
Closing this issue as won't fix.
