### ISSUE TITLE
Various git commands for contributing are missing from readme.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/fluidproject.org#18]
Various commands like git checkout , git status and many other commands are missing from the readme which are used to create a pull request and how to update your forked branch using terminal.

**Comment by aashimgarg** [comment]
@jhung is this required?

**Comment by sachin10101998** [comment]
@aashimgarg ReadMe file for a project concisely introduces and explains a project. Basics of Git and git commands shouldn't really be a part of it.

**Comment by johntharian** [comment]
I am a gsoc aspirant.
So, may I  solve this issue @aashimgarg

**Comment by aashimgarg** [comment]
Yes @johntharian

**Comment by jobara** [comment]
@aashimgarg and @johntharian I'm not sure that we need to include this level of information into the readme. I think working with git is probably a reasonable pre-requisite. Perhaps there should be a contributor guide added for some of the project governance type issues, but that will need to be determine more closely with the maintainers.

**Comment by AbdullahiAbdulkabir** [comment]
Yes thanks for clarifying @jobara @sachin10101998. In some open source contributions they use --sign-off command is this not also applicable here. I can see there is an agreement we are filling while contributing does that suffice for the T&C?

**Comment by jobara** [comment]
@AbdullahiAbdulkabir At the moment you need to digitally sign the CLA

**Comment by Akshat162001** [comment]
Made Changes in readme file..
