### ISSUE TITLE
Add the uglify plugin in the gruntfile.js

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/fluidproject.org#21]
This plugin is not present in the gruntfile . 
This plugin is very much important as it helps to minify or uglify all the javascript code, removing all the blank spaces so that when we request it from the server it takes much less time to compile.And i think that it is very much useful.

**Comment by aashimgarg** [comment]
Hey @jhung @jobara should i work on this?

**Comment by jobara** [comment]
I'm not sure how much it would help here in that there isn't much custom JS code. It would be easier to use the minified version of Infusion, and if we switch to that we should also just use a UIO build which will remove some unneeded code form Infusion.

**Comment by aashimgarg** [comment]
Ok. I got it.
We can add sass plugin as the fluidproject.org contains a lot of CSS . Sass files compile into well-formatted, standard CSS to use in your site or application.
@jobara ?

**Comment by jobara** [comment]
> Ok. I got it.
> We can add sass plugin as the fluidproject.org contains a lot of CSS . Sass files compile into well-formatted, standard CSS to use in your site or application.
> @jobara ?

This sounds like a different issue than what was originally proposed, and probably doesn't fit in the current discussion. Additionally it's something that might make sense to consider as part of the project when the site is being redeveloped, but it isn't yet clear what the styling requirements will be.

**Comment by aashimgarg** [comment]
Ok i will make it as a new issue!

**Comment by sachin10101998** [comment]
If 'taking less time to compile' is the major factor behind uglifying JS, I'd rather recommend minifying it. Minifying code speeds up page loading and it is also readable. Major browsers minify the code before execution anyway. Some libraries like UglifyJS does minification when used, by removing unnecessary parts. But in general, Uglifying is making the code unreadable. 
Moreover, minifying can be reversed back when needed, whereas if we uglify it, there's no way to reverse it back.

**Comment by jobara** [comment]
> Ok. I got it.
> We can add sass plugin as the fluidproject.org contains a lot of CSS . Sass files compile into well-formatted, standard CSS to use in your site or application.
> @jobara ?

This has been filed as https://github.com/fluid-project/fluidproject.org/issues/24

**Comment by jobara** [comment]
@sachin10101998 usually these tools also generate a source map; which the browser can use to render a human readable form of the code in the debugger.
