### ISSUE TITLE
The upper line of the link collides with the fluid community icons.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/fluidproject.org#22]
## Describe the bug
When we click the fluid community icons , the upper line of the rectangle enclosing the link collides with the icons.
### To reproduce
1. Go to https://fluidproject.org/
2. Click on Fluid community web icon
3. See error

### Expected behavior
The upper line of the rectangle enclosing the link should not collide with fluid community web icon

## Screenshots
![Screenshot from 2020-02-26 22-42-51](https://user-images.githubusercontent.com/55639487/75369867-3b609b80-58ea-11ea-8e2f-6eda0dea2a55.png)
### Desktop
 - OS: [Ubuntu 18.04 ]
 - Browser [e.g. chrome]

**Comment by aashimgarg** [comment]
@jobara should i work on this?

**Comment by jobara** [comment]
@aashimgarg regarding your steps to reproduce, I believe step 2 is about placing keyboard focus on the link. When I click it just transitions the page and doesn't show the focus styling at at all. 

Do you have any thoughts on what might be causing this issue?

**Comment by aashimgarg** [comment]
@jobara may be the text is placed just below the icon .They should be some space below the icon so that the upper line of the rectangle should not collide with it.
Should i work on this?
