### ISSUE TITLE
The background picture of featured work get disappeared.

### ISSUE THREAD

**Issue by Chaitanyassr** [fluid-project/fluidproject.org#28]
The background picture of featured work get disappeared when color and contrast is change from the initial value.
page link - https://fluidproject.org/
### To reproduce
1. Click on show display preferences
2. change the color and contrast

## Screenshots
![Screenshot (167)](https://user-images.githubusercontent.com/30374226/75608918-dbf0ce80-5b29-11ea-9037-63a4e42bedea.png)

## Technical details
 - Browser [e.g. chrome]

**Comment by nurulhassan** [comment]
@Chaitanyassr  Can u please elaborate this issue? i can`t see any problem related to this.

**Comment by Chaitanyassr** [comment]
> @Chaitanyassr Can u please elaborate this issue? i can`t see any problem related to this.

Please follow the "To reproduce" steps to see the problem.
