### ISSUE TITLE
Adding the social media icons in the footer. 

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/fluidproject.org#30]
## Is your feature request related to a problem?
No this issue is not related to any problem. But by this issue the user can easily come to know more about the floeproject.org and can contribute to it too.
## Describe the solution you'd like
We can add three icons or even more :-
1. Twitter icon :- This will help the user to read the tweets of the the organization.
2. Github icon :- This will help the user to contribute to the organization directly by clicking on the icon.
3. Mailing icon :- If the user has any query he can directly mail it to the org.

**Comment by aashimgarg** [comment]
@jobara should i work on this?

**Comment by Amulya-coder** [comment]
@jobara I want to contribute on this issue
