### ISSUE TITLE
CSSMin plugin for grunt.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/fluidproject.org#34]
CSSMin plugin for grunt will be very useful for the code as this repository contains a lot of css content in it.
This plugin is the CSS equivalent of Uglify. It simply gets any specified CSS files and minifies them.

**Comment by aashimgarg** [comment]
@jobara should i work on this?

**Comment by jobara** [comment]
It looks like the CSS is being generated from stylus, so it would probably be configuring stylus to minify. However, it's likely that many things will change for this site related to this project and work on this issue may not be relevant then.

**Comment by aashimgarg** [comment]
ok @jobara.
