### ISSUE TITLE
API call to fonts.googleapi blocked due to http connection

### ISSUE THREAD

**Issue by sachin10101998** [fluid-project/fluidproject.org#36]
## Describe the bug
The page at 'https://fluidproject.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700,100'. This request was blocked since the content must be served over HTTPS.

### To reproduce
1. Go to 'https://fluidproject.org/'
2. Right-click and Click on Inspect.
3. Go to Console

Screenshot:
![Screenshot from 2020-03-04 06-39-59](https://user-images.githubusercontent.com/34926285/75834904-6adc4000-5de3-11ea-967e-638998f54b92.png)

### Expected behavior
The API call should not be blocked

## Technical details
http is not secue and https calls must be based since the base host i.e. fluidproject.org is using https connection and api calls to http cannot be made.

### Desktop
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version : Latest

**Comment by jobara** [comment]
Has also been filed as https://issues.fluidproject.org/browse/FLUID-6462

**Comment by sachin10101998** [comment]
@jobara @jhung should #37 be merged? The error messages in the console go away on making changes suggested in #37.
