### ISSUE TITLE
Is github code latest?

### ISSUE THREAD

**Issue by Ayush23Dash** [fluid-project/fluidproject.org#39]
## Describe the bug
I had started working on the fluid project and wanted to simply extract every file(that are html,css, js files) and then convert them into my own custom made website(completely identical to the original fluid website) and then migrate it to Hugo.
While trying to understand the code,I made a local folder and started recreating the project but the index.html file in the fluid repo is somewhat different to what is hosted on fluidproject.org/index.html
I believe the code on github is not the latest,though there are very minor differences.

## Screenshots
Though this is a minor issue that displays Learn More link ahead of the first line but its different than the actual fluid website where there is a link only ahead of the second line
![fluid](https://user-images.githubusercontent.com/40827680/76161934-0bbd5900-615e-11ea-9263-56bc71054bbd.png)

### Desktop
 - OS: Windows
 - Browser : Chrome
 - Version 80

## Additional context or notes
I believe that issue is the version of the github code,apologies if I am wrong.

**Comment by Ayush23Dash** [comment]
@jobara  @jhung  please help!

**Comment by jobara** [comment]
@Ayush23Dash could you please explain more about how you extracted the files? The fluid project website is built using docpad, so you would need to run any of it's files through the docpad generation. It could be that parts are missing because of that. The floe project site does not currently use any CMS or Static Site Generator.

**Comment by jobara** [comment]
@Ayush23Dash thanks for providing the example. We'd have to consider the design. However, with the site potentially changing with the proposed GSoC project. This may be something that should be re-evaluated with that process. @jhung thoughts?

**Comment by Ayush23Dash** [comment]
@jobara i have literally extracted code from the index.html file and other files and now i am working on a completely new version of the website using nodejs(obviously the code's skeleton structure is copied from the floe repo) and after getting that done i will be migrating to hugo.
And yes today I will be working on the Floe website by trying to understand the code structure (i feel that is easy because in it there is hard coded html).
Is my approach correct?

**Comment by jobara** [comment]
@Ayush23Dash I'll start by answering the question from the issue title. Yes, what's in master is the latest. However, the site might be behind a bit. I believe we have to deploy a change or two, but they are small.

Could you please explain your process for extracting? I'm still not sure what you did. Did you just copy and past what was in the HTML file from the rendered fluidproject.org site? Also not sure what the purpose for the extraction is, but maybe that will be more clear when I better understand what you are doing. At any rate, I'm going to close this issue and maybe it would be better to move this discussion to the fluid-work mailing list or IRC Channel.
