### ISSUE TITLE
improving the visibility of navbar active tag

### ISSUE THREAD

**Issue by nurulhassan** [fluid-project/fluidproject.org#55]
The navbar tag element ui can be optimized so that the active tag can be visible to the user and also it also matches with the website theme. @jobara  if it looks good then it can be improved according to your point of view.

## Describe alternative solutions you've considered
the current active hover color can be changed to the current theme as it will match the current website theme.
Current navbar active tab view
![old](https://user-images.githubusercontent.com/33507767/79892623-7382e700-8420-11ea-9b5a-e87a8a82eaa8.PNG)

updated view with the matching website UI
![updated](https://user-images.githubusercontent.com/33507767/79892695-8990a780-8420-11ea-9961-2f8f4058fc25.PNG)

**Comment by nurulhassan** [comment]
@jhung please have a look on this.

**Comment by jobara** [comment]
@nurulhassan we're planning to redesign this site soon. We can consider this issue along with that  redesign process, but it likely isn't something we'll be looking at until then.

**Comment by nurulhassan** [comment]
our first priority is to migrate our website to some static site using
static site generator.

**Comment by nurulhassan** [comment]
Sir, I think it will be good if we use CI/CD method at the time of
Migrating the Floe and fluid website through static site generator(Hugo,
etc) and will also help us to optimise the UI of the website at the same
time.

**Comment by cggvuhh** [comment]
Can anyone tell that is inclusion design institute organisation applying for  2021gsoc 

@jobara @avtar @cindlyi

**Comment by greatislander** [comment]
Hi, we won't be making this change for now.
