### ISSUE TITLE
netlify-plugin-checklinks fragment check errors

### ISSUE THREAD

**Issue by gtirloni** [fluid-project/fluidproject.org#71]
## Describe the bug

Netlify's check-links plugin is complaining about this in many files:

```
8:37:06 PM:   ✖ FAIL fragment-check dist/news/index.html --> #fluid-web-content
8:37:06 PM:   | operator: fragment-check
8:37:06 PM:   | expected: id="fluid-web-content"
8:37:06 PM:   |       at: dist/news/index.html:4:922 <a href="#fluid-web-content">...</a>
```

The fragment seems to be located in `src/_includes/partials/header.html`

## Screenshots
https://app.netlify.com/sites/fluid-fluidproject-org/deploys/5f9f4681dc2f17e6f931ba98

**Comment by greatislander** [comment]
The issue is that the skip to content link is trying to link to an ID that doesn't exist on the page. I'm opening a PR to address.
