### ISSUE TITLE
linting fails due to missing dependency for eslint-config-fluid

### ISSUE THREAD

**Issue by jobara** [fluid-project/fluidproject.org#73]
## Describe the bug

The [.eslintrc.json file extends `eslint-config-fluid`](https://github.com/fluid-project/fluidproject.org/blob/f0301ed1f2b8d2b07ef5efd5277343b48d201b4f/.eslintrc.json#L2); however, it isn't included as a dependency so is not available to use.

### To reproduce

1. from the terminal run `npm install`
2. run `npm run lint`
3. Notice that warning: "Warning: Cannot find module 'eslint-config-fluid'"

### Expected behavior

Linting should run without errors or warnings.

**Comment by greatislander** [comment]
Weird. I looked back through the history and appears that this dependency was removed during the Eleventy conversion: https://github.com/fluid-project/fluidproject.org/commit/1b738cd46fb633d2fdca2eef67329a48e3d86815#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by cggvuhh** [comment]
anyone tell me if this organization apply for GSoC 2021

**Comment by gtirloni** [comment]
> anyone tell me if this organization apply for GSoC 2021

We are not applying for GSoC this year.

**Comment by Proeditor07** [comment]
And now this year GSOC 2022 are you applying?

**Comment by greatislander** [comment]
Resolved in #89.
